### ISSUE TITLE
TotalSegmentator in Windows 11

### ISSUE THREAD

**Issue by rbumm** [wasserth/TotalSegmentator#10]
Please advise how to install and run TotalSegmentator in Windows 11. 

What I tried on a laptop with a Nvidia RTX 1060 GPU and Pytorch installed: 

````pip install TotalSegmentator````

from Powershell - no errors, but running TotalSegmentator results in 

![image](https://user-images.githubusercontent.com/18140094/186868086-19f37b16-8909-4b1e-9387-48d2e2830d0d.png)

What I also tried: 

````pip install TotalSegmentator````

from Windows WSL Ubuntu, but running Totalsegmentator threw an exception that Xvfb is missing

Any ideas? Thank you.

**Comment by joshy** [comment]
Hi,

thanks for trying out. I have no Windows Laptop at hand to try out but you could try the following command from Windows WSL Ubuntu (does `nvidia-smi` works in WSL?):
`TotalSegmentator -i <your-input-file-as-nifti> -o <your-outputdirectory>`.
As we rely on [nnUNet](https://github.com/MIC-DKFZ/nnUNet/) which does not support windows we also can't support it. Also please note there is no user interface available, you can only run it from the command line.

**Comment by rbumm** [comment]
That is what I did but I get
 
````RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
````
Although CUDA is up and running on my WSL2 Ubuntu installation

**Comment by rbumm** [comment]
nvidia-smi
Sun Aug 28 21:35:28 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
|  0%   55C    P8    17W / 290W |    865MiB /  8192MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by rbumm** [comment]
Thank you for your time in looking into this.

```
sudo pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/w
hl/cu116
```

Pytorch is available then. 

Another test on WSL Ubuntu: 

```
sudo TotalSegmentator -i ./input.nii.gz  -o output.nii.gz
Resampling...
Predicting part 0 of 5 ...
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:146: UserWarning:
NVIDIA GeForce RTX 3070 Ti with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "/usr/local/bin/TotalSegmentator", line 123, in <module>
    main()
  File "/usr/local/bin/TotalSegmentator", line 103, in main
    seg = nnUNet_predict_image(args.input, args.output, task_id, model="3d_fullres", folds=folds,
  File "/usr/local/lib/python3.8/dist-packages/totalsegmentator/nnunet.py", line 155, in nnUNet_predict_image
    nnUNet_predict(tmp_dir, tmp_dir, tid, model, folds, trainer, tta)
  File "/usr/local/lib/python3.8/dist-packages/totalsegmentator/nnunet.py", line 99, in nnUNet_predict
    predict_from_folder(model_folder_name, dir_in, dir_out, folds, save_npz, num_threads_preprocessing,
  File "/usr/local/lib/python3.8/dist-packages/nnunet/inference/predict.py", line 657, in predict_from_folder
    return predict_cases_fastest(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/usr/local/lib/python3.8/dist-packages/nnunet/inference/predict.py", line 487, in predict_cases_fastest
    res = trainer.predict_preprocessed_data_return_seg_and_softmax(d, do_mirroring=do_tta,
  File "/usr/local/lib/python3.8/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 211, in predict_preprocessed_data_return_seg_and_softmax
    ret = super().predict_preprocessed_data_return_seg_and_softmax(data,
  File "/usr/local/lib/python3.8/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 516, in predict_preprocessed_data_return_seg_and_softmax
    ret = self.network.predict_3D(data, do_mirroring=do_mirroring, mirror_axes=mirror_axes,
  File "/usr/local/lib/python3.8/dist-packages/nnunet/network_architecture/neural_network.py", line 147, in predict_3D
    res = self._internal_predict_3D_3Dconv_tiled(x, step_size, do_mirroring, mirror_axes, patch_size,
  File "/usr/local/lib/python3.8/dist-packages/nnunet/network_architecture/neural_network.py", line 345, in _internal_predict_3D_3Dconv_tiled
    gaussian_importance_map = gaussian_importance_map.half()
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x7fd760cb1fd0>
AttributeError: 'DummyFile' object has no attribute 'flush'
```

**Comment by wasserth** [comment]
It seems like you have to install another CUDA version which is compatible with your GPU.

**Comment by wasserth** [comment]
To run it on windows you could also try the comment here: https://github.com/wasserth/TotalSegmentator/issues/6#issuecomment-1220341631
But not sure if this really works.

**Comment by rbumm** [comment]
Thank you.  I now understand that I need to run TotalSegmentator with Python in the Windows setting. 

When I pip install totalsegmentator in a Windows 11 Powershell and run it the program downloads 5 models upon its first run and then throws an EOFError. This is not yet taking into account [#6 (comment)](https://github.com/wasserth/TotalSegmentator/issues/6#issuecomment-1220341631) ...

```
python TotalSegmentator -i test.nii.gz -o segmentation -v

Resampling...
  from shape (512, 512, 304) to shape (237, 237, 203)
Predicting part 0 of 5 ...
using model stored in  C:\Users\Rudolf\.totalsegmentator\nnunet\results\nnUNet\3d_fullres\Task251_TotalSegmentator_part1_organs_1139subj\nnUNetTrainerV2_ep4000_nomirror__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['s01']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, [0]
using the following model files:  ['C:\\Users\\Rudolf\\.totalsegmentator\\nnunet\\results\\nnUNet\\3d_fullres\\Task251_TotalSegmentator_part1_organs_1139subj\\nnUNetTrainerV2_ep4000_nomirror__nnUNetPlansv2.1\\fold_0\\model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
Traceback (most recent call last):
  File "C:\Users\Rudolf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\TotalSegmentator", line 123, in <module>
    main()
  File "C:\Users\Rudolf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\TotalSegmentator", line 103, in main
    seg = nnUNet_predict_image(args.input, args.output, task_id, model="3d_fullres", folds=folds,
  File "C:\Users\Rudolf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\totalsegmentator\nnunet.py", line 155, in nnUNet_predict_image
    nnUNet_predict(tmp_dir, tmp_dir, tid, model, folds, trainer, tta)
  File "C:\Users\Rudolf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\totalsegmentator\nnunet.py", line 99, in nnUNet_predict
    predict_from_folder(model_folder_name, dir_in, dir_out, folds, save_npz, num_threads_preprocessing,
  File "C:\Users\Rudolf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nnunet\inference\predict.py", line 657, in predict_from_folder
    return predict_cases_fastest(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "C:\Users\Rudolf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nnunet\inference\predict.py", line 469, in predict_cases_fastest
    for preprocessed in preprocessing:
  File "C:\Users\Rudolf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nnunet\inference\predict.py", line 109, in preprocess_multithreaded
    pr.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x000001E963442430>: attribute lookup <lambda> on nnunet.utilities.nd_softmax failed
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
PS C:\Users\Rudolf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by rbumm** [comment]
Update: 

Taking  https://github.com/wasserth/TotalSegmentator/issues/6#issuecomment-1220341631 into account TotalSegmentator now runs without errors in a Windows Powershell. 

I added
````
import sys
if 'win' in sys.platform:
    #fix for windows platform
    import pathos
    Process = pathos.helpers.mp.Process
    Queue = pathos.helpers.mp.Queue
else:
    from multiprocessing import Process, Queue
```

**Comment by wasserth** [comment]
Great to hear that it works in windows now!

**Comment by rbumm** [comment]
@wasserth I edited the nnunet which was installed automatically. But it would be great for windows users to get this fix included in nnunet so I created a PR: 

[https://github.com/MIC-DKFZ/nnUNet/pull/1155/files](https://github.com/MIC-DKFZ/nnUNet/pull/1155/files)

**Comment by lmdulz** [comment]
I have the same window popping up as @rbumm showed in his [first](https://github.com/wasserth/TotalSegmentator/issues/10#issue-1351971078) comment here. The installation worked fine with 
`pip install TotalSegmentator` 

But it happens for me when I try to run `TotalSegmentator -i <your-input-file-as-nifti> -o <your-outputdirectory>`

when I run it in my VS Code terminal on win 10 I'll get:

`PS C:\Users\Luca\Work\TotalSegmentator> TotalSegmentator -i "C:\Users\Luca\Desktop\dcm2nii\dcm2nii_LAE_Intensiv_Inte_Notfalle_20170808134057_401a.nii.gz" -o "C:\Users\Luca\Desktop\dcm2ii\dcm2nii_LAE_Innii\" -v`

**Comment by lmdulz** [comment]
I checked that as soon as I saw your fix. But I did already have that snippet in my  .\nnunet\inference\predict.py

**Comment by wasserth** [comment]
I have a windows fix in my own fork of nnunet which is used by TotalSegmentator.

**Comment by lmdulz** [comment]
> I have a windows fix in my own fork of nnunet which is used by TotalSegmentator.

Is your win fix any different from @rbumm 's adjustment [here?](https://github.com/wasserth/TotalSegmentator/issues/10#issuecomment-1234160460), bc I got TotalSegmentator two days ago and it has exactly the same lines of code.

Do I miss anything here?
