### ISSUE TITLE
Running as new thread impossible

### ISSUE THREAD

**Issue by dvnie1** [wasserth/TotalSegmentator#104]
If I try to use the python api and try running TotalSegmentator in a new thread, I get the following error over and over again, until I kill the script:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\cserd\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cserd\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 129, in _main
    prepare(preparation_data)
  File "C:\Users\cserd\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\cserd\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\cserd\PycharmProjects\ai-fistula-prediction\src\main.py", line 8, in <module>
    app = Flask(__name__)
          ^^^^^^^^^^^^^^^
  File "C:\Users\cserd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 566, in __init__
    super().__init__(
  File "C:\Users\cserd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\scaffold.py", line 112, in __init__
    root_path = get_root_path(self.import_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cserd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\helpers.py", line 631, in get_root_path
    raise RuntimeError(
RuntimeError: No root path can be found for the provided module '__mp_main__'. This can happen because the module came from an import hook that does not provide file name information or because it's a namespace package. In this case the root path needs to be explicitly provided.

This happens on MacOS, Linux and Windows. It is important to note, that I'm running TotalSegmentator from a Flask app. This is also the reason I need multithreading, so that the server stays responsive  while the segmentation is happening.

Does anyone have an idea on how this issue can be fixed?

(I'm willing to use TotalSegmentator for a webapp, which makes outcome predictions in certain types of operations based on ct  images and a large AI model)

**Comment by wasserth** [comment]
Unfortunately I do not really have an idea what this issue might be. Seems related to the way you do multithreading in your flask app.

**Comment by dvnie1** [comment]
The issue was resolved by setting the FLASK_APP environment variable to my application's main Python file (typically main.py or app.py) and then using the flask run command to start the development server.

Seps:

Open the terminal or command prompt.
Navigate to the project's directory using the cd command.
Set the FLASK_APP environment variable to the name of the main Python file (e.g., main.py) using the following command:
export FLASK_APP=main.py
set FLASK_APP=main.py
Note: If you are using Windows, use set instead of export:
Start the Flask development server using the following command:
flask run

Happy coding!
