### ISSUE TITLE
Generating output segmentations for some .nii.gz scans but not others

### ISSUE THREAD

**Issue by EmergentBehaviour** [wasserth/TotalSegmentator#105]
Recently been using TotalSegmentator iteratively through an internal dataset using the python api, however have had the issue where it will work fine for some segmentations (using .nii.gz CT scan files) but will fail midway through others, seemingly having to do with some temp directory or file cache not being found. Has anyone else had experience with this? Have yet to find anything in the scan nifti headers that would be out of the ordinary.

The output gets to "Predicting Part 1 of 5" before the following error:

```
Traceback` (most recent call last):
  File "workspace/totalseg_predict.py", line 20, in <module>
    totalsegmentator(file_path, curr_output)
  File "/opt/conda/lib/python3.8/site-packages/totalsegmentator/python_api.py", line 193, in totalsegmentator
    seg_img = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
  File "/opt/conda/lib/python3.8/site-packages/totalsegmentator/nnunet.py", line 271, in nnUNet_predict_image
    (tmp_dir / f"{img_part}.nii.gz").rename(tmp_dir / "parts" / f"{img_part}_{tid}.nii.gz")
  File "/opt/conda/lib/python3.8/pathlib.py", line 1359, in rename
    self._accessor.rename(self, target)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/nnunet_tmp_zmtfppxs/s01.nii.gz' -> '/tmp/nnunet_tmp_zmtfppxs/parts/s01_251.nii.gz'
```

When running TotalSegmentator through CLI to try again, a similar error occurs:
```
Traceback (most recent call last):
  File "/opt/conda/bin/TotalSegmentator", line 98, in <module>
    main()
  File "/opt/conda/bin/TotalSegmentator", line 91, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "/opt/conda/lib/python3.8/site-packages/totalsegmentator/python_api.py", line 193, in totalsegmentator
    seg_img = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
  File "/opt/conda/lib/python3.8/site-packages/totalsegmentator/nnunet.py", line 271, in nnUNet_predict_image
    (tmp_dir / f"{img_part}.nii.gz").rename(tmp_dir / "parts" / f"{img_part}_{tid}.nii.gz")
  File "/opt/conda/lib/python3.8/pathlib.py", line 1359, in rename
    self._accessor.rename(self, target)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/nnunet_tmp_qede1nhw/s01.nii.gz' -> '/tmp/nnunet_tmp_qede1nhw/parts/s01_251.nii.gz'
```

**Comment by wasserth** [comment]
There happened some error before that and therefore the tmp file is missing. You can probably see the error message when using "--verbose". Can you run again with that and then post the entire error message?

**Comment by EmergentBehaviour** [comment]
Running verbose shows the issue was the scan having no orthonormal cosines when loading the file with SimpleITK, though I have yet to see any major differences between image info that would cause it over earlier scans.

Output:

```
tmp_dir: /tmp/nnunet_tmp_qg41hfub
Resampling...
  from shape (512, 512, 93) to shape (267, 267, 310)
  Resampled in 8.57s
Predicting part 1 of 5 ...
using model stored in  /root/.totalsegmentator/nnunet/results/nnUNet/3d_fullres/Task251_TotalSegmentator_part1_organs_1139subj/nnUNetTrainerV2_ep4000_nomirror__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['s01']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, [0]
using the following model files:  ['/root/.totalsegmentator/nnunet/results/nnUNet/3d_fullres/Task251_TotalSegmentator_part1_organs_1139subj/nnUNetTrainerV2_ep4000_nomirror__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
preprocessing /tmp/nnunet_tmp_qg41hfub/s01.nii.gz
using preprocessor GenericPreprocessor
error in ['/tmp/nnunet_tmp_qg41hfub/s01_0000.nii.gz']
Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:1980:
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!
This worker has ended successfully, no errors to report
inference done. Now waiting for the segmentation export to finish...
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is /root/.totalsegmentator/nnunet/results/nnUNet/3d_fullres/Task251_TotalSegmentator_part1_organs_1139subj/nnUNetTrainerV2_ep4000_nomirror__nnUNetPlansv2.1
Traceback (most recent call last):
  File "/opt/conda/bin/TotalSegmentator", line 98, in <module>
    main()
  File "/opt/conda/bin/TotalSegmentator", line 91, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "/opt/conda/lib/python3.8/site-packages/totalsegmentator/python_api.py", line 193, in totalsegmentator
    seg_img = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
  File "/opt/conda/lib/python3.8/site-packages/totalsegmentator/nnunet.py", line 271, in nnUNet_predict_image
    (tmp_dir / f"{img_part}.nii.gz").rename(tmp_dir / "parts" / f"{img_part}_{tid}.nii.gz")
  File "/opt/conda/lib/python3.8/pathlib.py", line 1359, in rename
    self._accessor.rename(self, target)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/nnunet_tmp_qg41hfub/s01.nii.gz' -> '/tmp/nnunet_tmp_qg41hfub/parts/s01_251.nii.gz
```

Currently investigating differences between the files to further troubleshoot.

**Comment by wasserth** [comment]
In this case you can do the following: https://github.com/wasserth/TotalSegmentator#typical-problems

**Comment by EmergentBehaviour** [comment]
Thank you, this worked on all but a faulty scan in the dataset that will be reprocessed; closing issue.
