### ISSUE TITLE
Error about --roi_subset

### ISSUE THREAD

**Issue by xiaoli26** [wasserth/TotalSegmentator#108]
$ totalSegmentator -i E:/nii/ct.nii.gz -o E:/segmentation -ta total --roi_subset sacrum

If you use this tool please cite: https://doi.org/10.48550/arXiv.2208.05868

Resampling...
  Resampled in 6.89s
Traceback (most recent call last):
  File "C:\Users\omnisky\AppData\Roaming\Python\Python310\Scripts\totalSegmentator", line 98, in <module>
    main()
  File "C:\Users\omnisky\AppData\Roaming\Python\Python310\Scripts\totalSegmentator", line 91, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "C:\Users\omnisky\AppData\Roaming\Python\Python310\site-packages\totalsegmentator\python_api.py", line 193, in totalsegmentator
    seg_img = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
  File "C:\Users\omnisky\AppData\Roaming\Python\Python310\site-packages\totalsegmentator\nnunet.py", line 249, in nnUNet_predict_image
    new_task_id.append(map_partname_to_taskid[part_name])
KeyError: 'class_map_part_muscles_v2'

--------------------------------------------------------------------------------------------------
I've tried some other names in "map_to_binary.py" with no output in the folder.
--------------------------------------------------------------------------------------------------

$ totalSegmentator -i E:/nii/ct.nii.gz -o E:/segmentation -ta total --roi_subset hip_bone

If you use this tool please cite: https://doi.org/10.48550/arXiv.2208.05868

Resampling...
  Resampled in 6.21s
  Predicted in 0.16s
Resampling...
Saving segmentations...
0it [00:00, ?it/s]
  Saved in 7.19s
(base)
---------------------------------------------------------------------------------------------------
Though, no file saved in the folder. However,  I got the nii file when I typed brain or colon.
I've updated to the latest version.

**Comment by wasserth** [comment]
Hi,
thanks for pointing out this bug. I pushed a fix to the master branch. If you install from master branch (`pip install git+https://github.com/wasserth/TotalSegmentator.git`) it should work now.

**Comment by xiaoli26** [comment]
New error comes out after the package updated:

$ totalSegmentator -i D:/sort1/ct.nii.gz -o E:/nii/101 --roi_subset hip_left hip_right sacrum
Traceback (most recent call last):
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\Scripts\totalSegmentator", line 4, in <module>
    __import__('pkg_resources').run_script('TotalSegmentator==1.5.5', 'TotalSegmentator')
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\pkg_resources\__init__.py", line 708, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\pkg_resources\__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "c:\users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\totalsegmentator-1.5.5-py3.9.egg\EGG-INFO\scripts\TotalSegmentator", line 103, in <module>
    main()
  File "c:\users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\totalsegmentator-1.5.5-py3.9.egg\EGG-INFO\scripts\TotalSegmentator", line 96, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\totalsegmentator-1.5.5-py3.9.egg\totalsegmentator\python_api.py", line 200, in totalsegmentator
    seg_img = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\totalsegmentator-1.5.5-py3.9.egg\totalsegmentator\nnunet.py", line 268, in nnUNet_predict_image
    nnUNet_predict(tmp_dir, tmp_dir, tid, model, folds, trainer, tta,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\totalsegmentator-1.5.5-py3.9.egg\totalsegmentator\nnunet.py", line 116, in nnUNet_predict
    predict_from_folder(model_folder_name, dir_in, dir_out, folds, save_npz, num_threads_preprocessing,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\nnunet\inference\predict.py", line 668, in predict_from_folder
    return predict_cases_fastest(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\nnunet\inference\predict.py", line 440, in predict_cases_fastest
    pool = Pool(num_threads_nifti_save)
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x000002710362EEB0>
AttributeError: 'DummyFile' object has no attribute 'flush'

If you use this tool please cite: https://doi.org/10.48550/arXiv.2208.05868



$ totalSegmentator -i D:/sort1/ct.nii.gz -o E:/nii/101 --roi_subset sacrum
Traceback (most recent call last):
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\Scripts\totalSegmentator", line 4, in <module>
    __import__('pkg_resources').run_script('TotalSegmentator==1.5.5', 'TotalSegmentator')
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\pkg_resources\__init__.py", line 708, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\pkg_resources\__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "c:\users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\totalsegmentator-1.5.5-py3.9.egg\EGG-INFO\scripts\TotalSegmentator", line 103, in <module>
    main()
  File "c:\users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\totalsegmentator-1.5.5-py3.9.egg\EGG-INFO\scripts\TotalSegmentator", line 96, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\totalsegmentator-1.5.5-py3.9.egg\totalsegmentator\python_api.py", line 200, in totalsegmentator
    seg_img = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\totalsegmentator-1.5.5-py3.9.egg\totalsegmentator\nnunet.py", line 268, in nnUNet_predict_image
    nnUNet_predict(tmp_dir, tmp_dir, tid, model, folds, trainer, tta,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\totalsegmentator-1.5.5-py3.9.egg\totalsegmentator\nnunet.py", line 116, in nnUNet_predict
    predict_from_folder(model_folder_name, dir_in, dir_out, folds, save_npz, num_threads_preprocessing,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\nnunet\inference\predict.py", line 668, in predict_from_folder
    return predict_cases_fastest(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\site-packages\nnunet\inference\predict.py", line 440, in predict_cases_fastest
    pool = Pool(num_threads_nifti_save)
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\omnisky\.conda\envs\totalsegmentator\lib\multiprocessing\spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x0000025877CF8D60>
AttributeError: 'DummyFile' object has no attribute 'flush'

If you use this tool please cite: https://doi.org/10.48550/arXiv.2208.05868

Resampling...
  Resampled in 6.48s
Predicting part 1 of 1 ...

**Comment by wasserth** [comment]
Seems like some multiprocessing error. In windows the multiprocessing in python is a bit of a problem. Can you try it on a mac or linux machine?

**Comment by xiaoli26** [comment]
It performed well on WSL2 ubuntu
