### ISSUE TITLE
TotalSegmentator fails to download model on macOS with Python <3.10

### ISSUE THREAD

**Issue by ASHISRAVINDRAN** [wasserth/TotalSegmentator#119]
Hi @wasserth 
I am Ashis, from the MITK development team (along with @kislinsk, @rfloca) working to integrate TotalSegmentator for our upcoming release. I want to report an issue we are facing very recently on macOS (Monterey, Ventura Intel/M1).
It seems urllib3, the HTTP library used by TotalSegmentator is crashing with the following error:
```
Traceback (most recent call last):
  File "/Users/ashis/environments/totalseg3.9/bin/TotalSegmentator", line 8, in <module>
    from totalsegmentator.python_api import totalsegmentator
  File "/Users/ashis/environments/totalseg3.9/lib/python3.9/site-packages/totalsegmentator/python_api.py", line 11, in <module>
    from totalsegmentator. libs import download_pretrained_weights
  File "/Users/ashis/environments/totalseg3.9/lib/python3.9/site-packages/totalsegmentator/libs.py", line 13, in <module>
    import requests
  File "/Users/ashis/environments/totalseg3.9/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/ashis/environments/totalseg3.9/lib/python3.9/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168
```

As you can see, the Python version is 3.9 on my Intel MacBook with Monterey OS.
Upon some investigation, I have found this issue to be linked to the latest `urllib3` release being unforgiving with Python < 3.10. Ref: [Here](https://github.com/urllib3/urllib3/issues/2168), the link in the error message.
Rightfully so, the  TotalSegmentator(urllib3) works all right if installed in a Python 3.10 virtual env on my MacBook.

It would be great if you can fix the version of the `urllib3` package e.g., to 1.26.15 explicitly and, other critical dependencies so that installations wouldn't break sooner or later due to such version conflicts & deprecations.

**Comment by wasserth** [comment]
Thanks for pointing this out. I will try to fix it.

**Comment by wasserth** [comment]
I pushed a fix to the master branch. Can you check if it works for you know?
