### ISSUE TITLE
How to convert .model to .pth

### ISSUE THREAD

**Issue by qingwang-usc** [wasserth/TotalSegmentator#138]
Dear authors:
  I found that the pretrained model format is .model and it only save the model parameters. Now I want to convert it to the format of .pt or .pth including the model structure and parameters, and I don't konw how to do it. Could you tell me how to convert? Thank you for your reply!

**Comment by wasserth** [comment]
The .model file is stored by nnunet. I never looked into the details of this file. You can ask on the nnunet site if they know how to convert it to .pth

**Comment by LongChenCV** [comment]
> Dear authors: I found that the pretrained model format is .model and it only save the model parameters. Now I want to convert it to the format of .pt or .pth including the model structure and parameters, and I don't konw how to do it. Could you tell me how to convert? Thank you for your reply!

Hi, have you converted .model to .pth? I'm trying to fine-tune the pretrained model (.model format downloaded) on my own dataset using 
'''nnUNetv2_train 101 3d_fullres 0 -tr nnUNetTrainerNoMirroring  -pretrained_weights  ~/fold_0/model_final_checkpoint.model'''

However, the following error occurs, I think this is because .pth is required by nnUNetv2_train rather than .model, how to solve this?

Traceback (most recent call last):
  File "/mnt/storage/home/lchen6/anaconda3/envs/totalseg/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/mnt/storage/home/lchen6/anaconda3/envs/totalseg/lib/python3.9/site-packages/nnunetv2/run/run_training.py", line 252, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/mnt/storage/home/lchen6/anaconda3/envs/totalseg/lib/python3.9/site-packages/nnunetv2/run/run_training.py", line 188, in run_training
    maybe_load_checkpoint(nnunet_trainer, continue_training, only_run_validation, pretrained_weights)
  File "/mnt/storage/home/lchen6/anaconda3/envs/totalseg/lib/python3.9/site-packages/nnunetv2/run/run_training.py", line 93, in maybe_load_checkpoint
    load_pretrained_weights(nnunet_trainer.network, pretrained_weights_file, verbose=True)
  File "/mnt/storage/home/lchen6/anaconda3/envs/totalseg/lib/python3.9/site-packages/nnunetv2/run/load_pretrained_weights.py", line 12, in load_pretrained_weights
    pretrained_dict = saved_model['network_weights']
KeyError: 'network_weights'
