### ISSUE TITLE
docker image error in pkg_resources with version conflict for tqdm

### ISSUE THREAD

**Issue by bergtholdt** [wasserth/TotalSegmentator#14]
When trying to run the docker image (via podman), I get the following error:

```sh
=============
== PyTorch ==
=============

NVIDIA Release 20.10 (build 16972326)
PyTorch Version 1.7.0a0+7036e91

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2020 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

Traceback (most recent call last):
  File "/opt/conda/bin/TotalSegmentator", line 123, in <module>
    main()
  File "/opt/conda/bin/TotalSegmentator", line 72, in main
    parser.add_argument('--version', action='version', version=require("TotalSegmentator")[0].version)
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tqdm 4.31.1 (/opt/conda/lib/python3.6/site-packages), Requirement.parse('tqdm>=4.45.0'), {'p-tqdm'})
```

Seems like tqdm is not installed with the reqired version for p-tqdm.

**Comment by wasserth** [comment]
Thanks for this hint. I fixed the tqdm version. When the docker container is rebuild (in roughly 1h) it should work.
