### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by angolin22** [wasserth/TotalSegmentator#149]
May I ask that what is the reason for this error?

```
Traceback (most recent call last):
  File "/opt/conda/bin/TotalSegmentator", line 103, in <module>
    main()
  File "/opt/conda/bin/TotalSegmentator", line 96, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "/opt/conda/lib/python3.8/site-packages/totalsegmentator/python_api.py", line 183, in totalsegmentator
    download_pretrained_weights(tid)
  File "/opt/conda/lib/python3.8/site-packages/totalsegmentator/libs.py", line 211, in download_pretrained_weights
    download_url_and_unpack(WEIGHTS_URL, config_dir)
  File "/opt/conda/lib/python3.8/site-packages/totalsegmentator/libs.py", line 86, in download_url_and_unpack
    raise e
  File "/opt/conda/lib/python3.8/site-packages/totalsegmentator/libs.py", line 82, in download_url_and_unpack
    with zipfile.ZipFile(config_dir / "tmp_download_file.zip", 'r') as zip_f:
  File "/opt/conda/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/opt/conda/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by angolin22** [comment]
ok, it's ok.

**Comment by yuanpengpeng** [comment]
> ok, it's ok.

Is it okay for you to try it the second time? Excuse me. I tried it once and found it still failed.
