### ISSUE TITLE
Problem LOAD DLL: Not Enough Memory

### ISSUE THREAD

**Issue by FranciscoFS** [wasserth/TotalSegmentator#150]
Hi everyone, im trying to run TotalSegmentator by command on my PC (Windows 16 gb RAM and RTX 3050Ti 4 gb) and im having the next issue

![image](https://github.com/wasserth/TotalSegmentator/assets/29107949/644b84ec-8a0e-4ca8-8eca-95e9ac460d6b)

(tf_2.4) PS C:\WINDOWS\system32> TotalSegmentator_bot -i "C:\Users\franc\Desktop\Pruebas\TEST.nii.gz" -o C:\Users\franc\Desktop\Pruebas -ta bones_tissue_test
C:\Users\franc\anaconda3\envs\tf_2.4\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\franc\anaconda3\envs\tf_2.4\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\franc\anaconda3\envs\tf_2.4\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

If you use this tool please cite: https://doi.org/10.48550/arXiv.2208.05868

Traceback (most recent call last):
  File "C:\Users\franc\anaconda3\envs\tf_2.4\Scripts\TotalSegmentator", line 103, in <module>
    main()
  File "C:\Users\franc\anaconda3\envs\tf_2.4\Scripts\TotalSegmentator", line 96, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "C:\Users\franc\anaconda3\envs\tf_2.4\lib\site-packages\totalsegmentator\python_api.py", line 38, in totalsegmentator
    from totalsegmentator.nnunet import nnUNet_predict_image  # this has to be after setting new env vars
  File "C:\Users\franc\anaconda3\envs\tf_2.4\lib\site-packages\totalsegmentator\nnunet.py", line 21, in <module>
    from nnunet.inference.predict import predict_from_folder
  File "C:\Users\franc\AppData\Roaming\Python\Python38\site-packages\nnunet\inference\predict.py", line 22, in <module>
    from nnunet.inference.segmentation_export import save_segmentation_nifti_from_softmax, save_segmentation_nifti
  File "C:\Users\franc\AppData\Roaming\Python\Python38\site-packages\nnunet\inference\segmentation_export.py", line 21, in <module>
    import SimpleITK as sitk
  File "C:\Users\franc\anaconda3\envs\tf_2.4\lib\site-packages\SimpleITK\__init__.py", line 18, in <module>
    from SimpleITK.SimpleITK import *
  File "C:\Users\franc\anaconda3\envs\tf_2.4\lib\site-packages\SimpleITK\SimpleITK.py", line 13, in <module>
    from . import _SimpleITK
ImportError: DLL load failed while importing _SimpleITK: Not enough memory resources are available to process this command.
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x0000014FC78D9730>
AttributeError: 'DummyFile' object has no attribute 'flush'

Anyone does know what is that DLL load failed... Not enough memory?
Is it my memory to low?

regards

**Comment by wasserth** [comment]
SimpleITK report that not enough memory is available. Maybe try to restart your computer to make sure all memory is freed and then try with a smaller CT image.
