### ISSUE TITLE
Installing weight files in python keeps failing

### ISSUE THREAD

**Issue by yuanpengpeng** [wasserth/TotalSegmentator#167]
Traceback (most recent call last):
  File "TotalSegmentator", line 108, in <module>
    main()
  File "TotalSegmentator", line 104, in main
    totalsegmentator(args.input, args.output, args.ml)
  File "/home/list0/anaconda3/envs/python37_yuanpeng/lib/python3.7/site-packages/totalsegmentator/python_api.py", line 183, in totalsegmentator
    download_pretrained_weights(tid)
  File "/home/list0/anaconda3/envs/python37_yuanpeng/lib/python3.7/site-packages/totalsegmentator/libs.py", line 211, in download_pretrained_weights
    download_url_and_unpack(WEIGHTS_URL, config_dir)
  File "/home/list0/anaconda3/envs/python37_yuanpeng/lib/python3.7/site-packages/totalsegmentator/libs.py", line 86, in download_url_and_unpack
    raise e
  File "/home/list0/anaconda3/envs/python37_yuanpeng/lib/python3.7/site-packages/totalsegmentator/libs.py", line 82, in download_url_and_unpack
    with zipfile.ZipFile(config_dir / "tmp_download_file.zip", 'r') as zip_f:
  File "/home/list0/anaconda3/envs/python37_yuanpeng/lib/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/home/list0/anaconda3/envs/python37_yuanpeng/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

When I run the totalseg_download_weights file in python, the download weights are always saved. After deleting the bad files, re-downloading still doesn’t work.

**Comment by wasserth** [comment]
Which version of TotalSegmentator are you using? 
I would recommend to delete  `~/.totalsegmentator` and try again.
