### ISSUE TITLE
Problems running TotalSegmentatorV2

### ISSUE THREAD

**Issue by elpequeno** [wasserth/TotalSegmentator#180]
Hi there,

I was checking out V2 and I was able to install it.

Running: `TotalSegmentator -i tmp/Example.nii.gz -o tmp/segmentationsv2/ -f`
works for me.

If I try to use it without the `--fast` option, I get the following error:
```
If you use this tool please cite: https://pubs.rsna.org/doi/10.1148/ryai.230024

Resampling...
  Resampled in 4.53s
Predicting part 1 of 5 ...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:01<00:00, 16.18it/s]
Predicting part 2 of 5 ...
Traceback (most recent call last):
  File "/data/an55321/anaconda3/env/totalsegv2/bin/TotalSegmentator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/an55321/anaconda3/env/totalsegv2/lib/python3.11/site-packages/totalsegmentator/bin/TotalSegmentator.py", line 129, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "/data/an55321/anaconda3/env/totalsegv2/lib/python3.11/site-packages/totalsegmentator/python_api.py", line 293, in totalsegmentator
    seg_img = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/an55321/anaconda3/env/totalsegv2/lib/python3.11/site-packages/totalsegmentator/nnunet.py", line 372, in nnUNet_predict_image
    nnUNetv2_predict(tmp_dir, tmp_dir, tid, model, folds, trainer, tta,
  File "/data/an55321/anaconda3/env/totalsegv2/lib/python3.11/site-packages/totalsegmentator/nnunet.py", line 205, in nnUNetv2_predict
    predictor.initialize_from_trained_model_folder(
  File "/data/an55321/anaconda3/env/totalsegv2/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 86, in initialize_from_trained_model_folder
    checkpoint = torch.load(join(model_training_output_dir, f'fold_{f}', checkpoint_name),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/an55321/anaconda3/env/totalsegv2/lib/python3.11/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/an55321/anaconda3/env/totalsegv2/lib/python3.11/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x7fc0823bdc90>
AttributeError: 'DummyFile' object has no attribute 'flush'
```

Any suggestions?

Thanks,
Andre

**Comment by wasserth** [comment]
This is strange. Maybe the download of the weights somehow failed and the downloaded weights are corrupted. You can try to remove the directory `~/.totalsegmentator` and run again. Then all weights will be newly downloaded.

**Comment by elpequeno** [comment]
Hi Jakob. Thanks for the suggestion. That helped with my local installation. Weird. Maybe the download failed yesterday or so.

I need to use TotalSegmentator in a Docker. If I use your provided Dockerfile or alternatively install it via pip inside a docker, I get the following result:

```
TotalSegmentator -i /in/converted_image.nii.gz -o /app/test

If you use this tool please cite: https://pubs.rsna.org/doi/10.1148/ryai.230024

TotalSegmentator sends anonymous usage statistics. If you want to disable it check the documentation.
Resampling...
  Resampled in 0.81s
Predicting part 1 of 5 ...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 18.11it/s]
Bus error (core dumped)
root@7f458668b14e:/workspace# /usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Any idea about this as well?

Thanks!

**Comment by wasserth** [comment]
This error does not seem familiar to me. I do not really have an idea what the issue might be.

**Comment by plessbd** [comment]
This might be related to the shared memory given to docker/podman you can specify more shared memory using for example:`--shm-size 2g` where 2g is a larger than default of 64m

**Comment by elpequeno** [comment]
That worked. Thanks Ben!

**Comment by wasserth** [comment]
Thanks for pointing this out. I always run my docker container with these options:
```
docker run --gpus 'device=0' --ipc=host 
```
I think this also fixes the shared memory problem.

**Comment by elpequeno** [comment]
Hi Jakob, 

I just tried your call and that also works for me. THanks for your help. I'll close this ticket.
