### ISSUE TITLE
Exception: gzip.BadGzipFile: CRC check failed 0xe7b9154e != 0xaf073076

### ISSUE THREAD

**Issue by yerramasu** [wasserth/TotalSegmentator#207]
Hello,

I am trying to retrain the new dataset v2 on Ubuntu 18. I was able to convert the dataset to nnUNet format as per th instuction. When I tried to execute nnUNetv2_plan_and_preprocess, I am getting below exception. I am not sure if I am doing anything wrong.

sing <class 'nnunetv2.imageio.nibabel_reader_writer.NibabelIOWithReorient'> reader/writer
  2%|███▏                                                                                                                            | 28/1139 [00:03<02:01,  9.11it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/storage1/nnunet2/TotalSegmentator/env/lib/python3.9/site-packages/acvl_utils/miscellaneous/ptqdm.py", line 43, in wrapper
    result = function(*enum_iterable[1], **kwargs)
  File "/home/ubuntu/storage1/nnunet2/TotalSegmentator/env/lib/python3.9/site-packages/nnunetv2/experiment_planning/dataset_fingerprint/fingerprint_extractor.py", line 84, in analyze_case
    images, properties_images = rw.read_images(image_files)
  File "/home/ubuntu/storage1/nnunet2/TotalSegmentator/env/lib/python3.9/site-packages/nnunetv2/imageio/nibabel_reader_writer.py", line 143, in read_images
    images.append(reoriented_image.get_fdata().transpose((2, 1, 0))[None])
  File "/home/ubuntu/storage1/nnunet2/TotalSegmentator/env/lib/python3.9/site-packages/nibabel/dataobj_images.py", line 373, in get_fdata
    data = np.asanyarray(self._dataobj, dtype=dtype)
  File "/home/ubuntu/storage1/nnunet2/TotalSegmentator/env/lib/python3.9/site-packages/nibabel/arrayproxy.py", line 439, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/home/ubuntu/storage1/nnunet2/TotalSegmentator/env/lib/python3.9/site-packages/nibabel/arrayproxy.py", line 406, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/home/ubuntu/storage1/nnunet2/TotalSegmentator/env/lib/python3.9/site-packages/nibabel/arrayproxy.py", line 376, in _get_unscaled
    return array_from_file(
  File "/home/ubuntu/storage1/nnunet2/TotalSegmentator/env/lib/python3.9/site-packages/nibabel/volumeutils.py", line 465, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "/usr/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.9/gzip.py", line 478, in read
    self._read_eof()
  File "/usr/lib/python3.9/gzip.py", line 524, in _read_eof
    raise BadGzipFile("CRC check failed %s != %s" % (hex(crc32),
gzip.BadGzipFile: CRC check failed 0xe7b9154e != 0xaf073076
"""

The above exception was the direct cause of the following exception:

Regards,
Anil

**Comment by SimonaBottani** [comment]
Hi, 

Thanks for the repo ! 
I have just encountered the same problem on the repo trying to retrain on nnUNet. @yerramasu how did you solve it ? 
I have re-download and re-converted the whole dataset but maybe it's a versioning problem

Thanks !
