### ISSUE TITLE
Docker container in user-mode

### ISSUE THREAD

**Issue by razorx89** [wasserth/TotalSegmentator#21]
Currently, the Docker container does not work in user-mode (started with `--user <uid>:<gid>`):

```
docker run --gpus 'device=0' --ipc=host --user $(id -u):$(id -g) -v <...>/workspace wasserth/totalsegmentator_container:master TotalSegmentator -i /workspace/test-wb.nii.gz -o /workspace/test-wb-segmentations --preview

=============
== PyTorch ==
=============

NVIDIA Release 20.10 (build 16972326)
PyTorch Version 1.7.0a0+7036e91

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2020 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

Matplotlib created a temporary config/cache directory at /tmp/matplotlib-szljy3md because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/opt/conda/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/.totalsegmentator/nnunet/results/nnUNet/3d_fullres'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/opt/conda/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/.totalsegmentator/nnunet/results/nnUNet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/opt/conda/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/.totalsegmentator/nnunet/results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/opt/conda/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/.totalsegmentator/nnunet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/TotalSegmentator", line 157, in <module>
    main()
  File "/opt/conda/bin/TotalSegmentator", line 87, in main
    setup_nnunet()
  File "/opt/conda/lib/python3.6/site-packages/totalsegmentator/libs.py", line 154, in setup_nnunet
    (config_dir / "nnunet/results/nnUNet/3d_fullres").mkdir(exist_ok=True, parents=True)
  File "/opt/conda/lib/python3.6/pathlib.py", line 1252, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/conda/lib/python3.6/pathlib.py", line 1252, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/conda/lib/python3.6/pathlib.py", line 1252, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  [Previous line repeated 1 more time]
  File "/opt/conda/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/opt/conda/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/.totalsegmentator'
```

User-mode would simplify scripting a lot, since all resulting artifacts would have the correct file access rights.

**Comment by wasserth** [comment]
Thanks for this hint. Do you know what I have to change to enable user-mode for a docker container?

**Comment by razorx89** [comment]
https://github.com/wasserth/TotalSegmentator/blob/323055aee8f45042a07c7c774c9375da20266a5f/totalsegmentator/libs.py#L161

Here, the home directory is not available for a container started in user-mode.

**Comment by wasserth** [comment]
I did those changes to the master branch. It should work now.

**Comment by razorx89** [comment]
Yes, it works. Thanks.
