### ISSUE TITLE
AttributeError: 'DummyFile' object has no attribute 'flush'

### ISSUE THREAD

**Issue by shifuxiao** [wasserth/TotalSegmentator#211]
hello ,can you help mi solve this error. when I run this code.                                                                                                                  
from totalsegmentator.python_api import totalsegmentator
import torch
print(torch.__version__)
input_path = r"E:\data\example_ct.nii.gz"
output_path = r"E:\data\dcm_ct_body\seg_result"
totalsegmentator(input_path, output_path, task="total",ml=True,body_seg=True)
If you use this tool please cite: https://pubs.rsna.org/doi/10.1148/ryai.230024
It raise this error.
Resampling...
  Resampled in 3.03s
Predicting part 1 of 5 ...
Traceback (most recent call last):
  File "D:\anaconda3\envs\TotalSegmentator\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\TotalSegmentator\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\TotalSegmentator\Scripts\TotalSegmentator.exe\__main__.py", line 7, in <module>
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\totalsegmentator\bin\TotalSegmentator.py", line 127, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\totalsegmentator\python_api.py", line 293, in totalsegmentator
    seg_img, ct_img = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\totalsegmentator\nnunet.py", line 375, in nnUNet_predict_image
    nnUNetv2_predict(tmp_dir, tmp_dir, tid, model, folds, trainer, tta,
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\totalsegmentator\nnunet.py", line 178, in nnUNetv2_predict
    predict_from_raw_data(dir_in,
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\nnunetv2\inference\predict_from_raw_data.py", line 221, in predict_from_raw_data
    inference_gaussian = inference_gaussian.to(device)
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: max_split_size_mb=32
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x000001F47A39EEB0>
AttributeError: 'DummyFile' object has no attribute 'flush'

**Comment by wasserth** [comment]
Unfortunately this error does not seem familiar to me.

**Comment by emckenzi123** [comment]
I am also seeing this error.  I tried both direct usage of the pip installed TotalSegmentator, as well as the Docker version.  Both methods give the same error as OP.  I am running this on Ubuntu 22.04

**Comment by shifuxiao** [comment]
Can you give mi you python environment about totalsegmentator txt.

**Comment by emckenzi123** [comment]
I was able to get this to work by using my base environment.  Previously, I was running the provided docker image in my base environment, and also tried running the executable within my own docker image.  From a casual look at the error messages, I wonder if there is a threading issue when this code is executed within a docker container.

**Comment by yigedabuliu** [comment]
Please find the following code segment A in totalsegmentator.libs.py and change it to B.
`#code segment A
class DummyFile(object):
    def write(self, x): pass`
`#code segment A
class DummyFile(object):
    def write(self, x): pass
    def flush(self): pass
`
Or specify verbose as true at runtime.
I hope this answer will help you.

**Comment by wasserth** [comment]
Thanks for pointing this out. I added flush to DummyFile. If you install TotalSegmentator from the master (https://github.com/wasserth/TotalSegmentator#install-latest-master-branch-contains-latest-bug-fixes) it should work. Does this solve your problem?

**Comment by yigedabuliu** [comment]
> Thanks for pointing this out. I added flush to DummyFile. If you install TotalSegmentator from the master (https://github.com/wasserth/TotalSegmentator#install-latest-master-branch-contains-latest-bug-fixes) it should work. Does this solve your problem?

You're welcome. It's a pleasure to help you.

**Comment by shifuxiao** [comment]
This error have solved.But it have new error.Can you help me solve it?
from totalsegmentator.python_api import totalsegmentator
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
if __name__ == '__main__':
    input_path = r"E:\fuxiaoshi\data\input\CT_test-volume-35.nii" #
    output_path = r"E:\fuxiaoshi\data\output\\"
    totalsegmentator(input_path, output_path,ml=False,device="gpu") 
D:\anaconda3\envs\TotalSegmentator\python.exe E:/fuxiaoshi/TotalSegmentation/ts_test.py
2.1.0
11.8
True

If you use this tool please cite: https://pubs.rsna.org/doi/10.1148/ryai.230024

Resampling...
  Resampled in 15.03s
Predicting part 1 of 5 ...
Traceback (most recent call last):
  File "E:\fuxiaoshi\TotalSegmentation\ts_test.py", line 19, in <module>
    totalsegmentator(input_path, output_path,ml=False,device="cpu") #,body_seg=True
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\totalsegmentator\python_api.py", line 293, in totalsegmentator
    seg_img, ct_img = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\totalsegmentator\nnunet.py", line 375, in nnUNet_predict_image
    nnUNetv2_predict(tmp_dir, tmp_dir, tid, model, folds, trainer, tta,
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\totalsegmentator\nnunet.py", line 178, in nnUNetv2_predict
    predict_from_raw_data(dir_in,
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\nnunetv2\inference\predict_from_raw_data.py", line 236, in predict_from_raw_data
    for preprocessed in mta:
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 201, in __next__
    self._start()
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 245, in _start
    gpu = torch.cuda.current_device()
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "D:\anaconda3\envs\TotalSegmentator\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: max_split_size_mb=32

**Comment by scarpma** [comment]
I have experienced problems with the multiprocess package. I think that the python api function should be called only inside the main environment, i.e.
```python
from totalsegmentator.python_api import totalsegmentator
if __name__ == "__main__":
    totalsegmentator(input_path, output_path)
```
and not like this
```python
from totalsegmentator.python_api import totalsegmentator
totalsegmentator(input_path, output_path)
```

So @wasserth I suggest editing the README.md file
https://github.com/wasserth/TotalSegmentator/blob/7825688c39bd03a4b4d50f8a375069c3e202ead8/README.md?plain=1#L143

**Comment by wasserth** [comment]
Thanks for pointing this out. I added this information to the readme.
