### ISSUE TITLE
bug : bones extremities segmentation task does not work

### ISSUE THREAD

**Issue by ivanstepanovftw** [wasserth/TotalSegmentator#238]
```
Traceback (most recent call last):
  File "/home/i/Downloads/Slicer-5.4.0-linux-amd64/bin/Python/slicer/util.py", line 3146, in tryWithErrorDisplay
    yield
  File "/home/i/Downloads/Slicer-5.4.0-linux-amd64/slicer.org/Extensions-31938/TotalSegmentator/lib/Slicer-5.4/qt-scripted-modules/TotalSegmentator.py", line 271, in onApplyButton
    self.logic.process(self.ui.inputVolumeSelector.currentNode(), self.ui.outputSegmentationSelector.currentNode(),
  File "/home/i/Downloads/Slicer-5.4.0-linux-amd64/slicer.org/Extensions-31938/TotalSegmentator/lib/Slicer-5.4/qt-scripted-modules/TotalSegmentator.py", line 790, in process
    self.readSegmentation(outputSegmentation, outputSegmentationFile, task)
  File "/home/i/Downloads/Slicer-5.4.0-linux-amd64/slicer.org/Extensions-31938/TotalSegmentator/lib/Slicer-5.4/qt-scripted-modules/TotalSegmentator.py", line 864, in readSegmentation
    labelValueToSegmentName = class_map[task]
KeyError: 'bones_extremities'
```
Using CPU only on Fedora. Reproduce is as usual: selected bones extremities, create new segmentation on apply, then clicked on Apply.
More logs

<details><summary>Details</summary>
<p>

```
Processing started
Writing input file to /tmp/Slicer-i/__SlicerTemp__2023-11-26_09+37+05.403/total-segmentator-input.nii
Creating segmentations with TotalSegmentator AI (pre-run)...
Total Segmentator arguments: ['-i', '/tmp/Slicer-i/__SlicerTemp__2023-11-26_09+37+05.403/total-segmentator-input.nii', '-o', '/tmp/Slicer-i/__SlicerTemp__2023-11-26_09+37+05.403/segmentation', '--fast']
/home/i/Downloads/Slicer-5.4.0-linux-amd64/lib/Python/bin/TotalSegmentator:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import require
/home/i/Downloads/Slicer-5.4.0-linux-amd64/lib/Python/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
/home/i/Downloads/Slicer-5.4.0-linux-amd64/lib/Python/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py:125: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn(
/home/i/Downloads/Slicer-5.4.0-linux-amd64/lib/Python/lib/python3.9/site-packages/torch/amp/autocast_mode.py:250: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(

If you use this tool please cite: https://doi.org/10.48550/arXiv.2208.05868

No GPU detected. Running on CPU. This can be very slow. The '--fast' option can help to some extend.
Using 'fast' option: resampling to lower resolution (3mm)
Resampling...
  Resampled in 3.14s
Predicting...

If you use this tool please cite: https://doi.org/10.48550/arXiv.2208.05868

No GPU detected. Running on CPU. This can be very slow. The '--fast' option can help to some extend.
Using 'fast' option: resampling to lower resolution (3mm)
Resampling...
  Resampled in 3.14s
Predicting...
  Predicted in 10.04s
Resampling...
Saving segmentations...

  0%|          | 0/104 [00:00<?, ?it/s]
  1%|          | 1/104 [00:11<20:03, 11.69s/it]
  7%|▋         | 7/104 [00:12<02:13,  1.38s/it]
  8%|▊         | 8/104 [00:15<02:36,  1.63s/it]
  9%|▊         | 9/104 [00:15<02:08,  1.35s/it]
 10%|▉         | 10/104 [00:15<01:41,  1.08s/it]
 12%|█▎        | 13/104 [00:16<00:53,  1.69it/s]
 13%|█▎        | 14/104 [00:16<00:54,  1.66it/s]
 14%|█▍        | 15/104 [00:17<01:02,  1.44it/s]
 15%|█▌        | 16/104 [00:18<00:55,  1.59it/s]
 17%|█▋        | 18/104 [00:18<00:34,  2.47it/s]
 18%|█▊        | 19/104 [00:18<00:35,  2.41it/s]
 19%|█▉        | 20/104 [00:18<00:28,  2.95it/s]
 20%|██        | 21/104 [00:19<00:24,  3.43it/s]
 21%|██        | 22/104 [00:20<00:39,  2.06it/s]
 22%|██▏       | 23/104 [00:20<00:32,  2.47it/s]
 23%|██▎       | 24/104 [00:20<00:26,  3.04it/s]
 24%|██▍       | 25/104 [00:21<00:30,  2.56it/s]
 25%|██▌       | 26/104 [00:21<00:26,  2.94it/s]
 26%|██▌       | 27/104 [00:21<00:21,  3.61it/s]
 27%|██▋       | 28/104 [00:21<00:23,  3.23it/s]
 28%|██▊       | 29/104 [00:22<00:24,  3.12it/s]
 30%|██▉       | 31/104 [00:22<00:21,  3.34it/s]
 31%|███       | 32/104 [00:23<00:24,  2.94it/s]
 33%|███▎      | 34/104 [00:23<00:19,  3.56it/s]
 34%|███▎      | 35/104 [00:23<00:21,  3.21it/s]
 36%|███▌      | 37/104 [00:24<00:18,  3.66it/s]
 37%|███▋      | 38/104 [00:24<00:21,  3.12it/s]
 38%|███▊      | 39/104 [00:25<00:20,  3.19it/s]
 38%|███▊      | 40/104 [00:25<00:17,  3.65it/s]
 39%|███▉      | 41/104 [00:25<00:23,  2.67it/s]
 41%|████▏     | 43/104 [00:26<00:18,  3.26it/s]
 42%|████▏     | 44/104 [00:26<00:19,  3.15it/s]
 43%|████▎     | 45/104 [00:27<00:26,  2.19it/s]
 44%|████▍     | 46/104 [00:27<00:24,  2.33it/s]
 45%|████▌     | 47/104 [00:29<00:44,  1.28it/s]
 47%|████▋     | 49/104 [00:30<00:28,  1.91it/s]
 48%|████▊     | 50/104 [00:30<00:24,  2.17it/s]
 49%|████▉     | 51/104 [00:30<00:20,  2.62it/s]
 50%|█████     | 52/104 [00:30<00:16,  3.06it/s]
 51%|█████     | 53/104 [00:31<00:18,  2.78it/s]
 53%|█████▎    | 55/104 [00:31<00:14,  3.40it/s]
 54%|█████▍    | 56/104 [00:31<00:14,  3.39it/s]
 55%|█████▍    | 57/104 [00:31<00:12,  3.86it/s]
 56%|█████▌    | 58/104 [00:32<00:10,  4.21it/s]
 57%|█████▋    | 59/104 [00:32<00:12,  3.59it/s]
 59%|█████▊    | 61/104 [00:32<00:10,  4.21it/s]
 60%|█████▉    | 62/104 [00:33<00:10,  3.86it/s]
 61%|██████    | 63/104 [00:33<00:09,  4.13it/s]
 62%|██████▏   | 64/104 [00:33<00:08,  4.45it/s]
 62%|██████▎   | 65/104 [00:34<00:11,  3.47it/s]
 64%|██████▍   | 67/104 [00:34<00:08,  4.32it/s]
 65%|██████▌   | 68/104 [00:34<00:11,  3.15it/s]
 66%|██████▋   | 69/104 [00:35<00:10,  3.21it/s]
 67%|██████▋   | 70/104 [00:35<00:09,  3.74it/s]
 68%|██████▊   | 71/104 [00:35<00:10,  3.00it/s]
 70%|███████   | 73/104 [00:36<00:07,  4.20it/s]
 71%|███████   | 74/104 [00:36<00:08,  3.48it/s]
 72%|███████▏  | 75/104 [00:36<00:08,  3.42it/s]
 73%|███████▎  | 76/104 [00:37<00:07,  3.75it/s]
 74%|███████▍  | 77/104 [00:37<00:07,  3.44it/s]
 76%|███████▌  | 79/104 [00:37<00:05,  4.88it/s]
 77%|███████▋  | 80/104 [00:37<00:05,  4.00it/s]
 78%|███████▊  | 81/104 [00:38<00:05,  3.92it/s]
 79%|███████▉  | 82/104 [00:38<00:05,  4.12it/s]
 80%|███████▉  | 83/104 [00:38<00:05,  3.87it/s]
 82%|████████▏ | 85/104 [00:38<00:03,  5.56it/s]
 83%|████████▎ | 86/104 [00:39<00:04,  4.38it/s]
 84%|████████▎ | 87/104 [00:39<00:04,  4.07it/s]
 85%|████████▍ | 88/104 [00:39<00:04,  3.87it/s]
 86%|████████▌ | 89/104 [00:40<00:03,  3.76it/s]
 88%|████████▊ | 91/104 [00:40<00:02,  5.52it/s]
 88%|████████▊ | 92/104 [00:40<00:02,  4.29it/s]
 89%|████████▉ | 93/104 [00:40<00:02,  4.35it/s]
 90%|█████████ | 94/104 [00:41<00:02,  3.77it/s]
 91%|█████████▏| 95/104 [00:41<00:02,  3.75it/s]
 93%|█████████▎| 97/104 [00:41<00:01,  5.29it/s]
 94%|█████████▍| 98/104 [00:42<00:01,  4.40it/s]
 95%|█████████▌| 99/104 [00:42<00:01,  4.50it/s]
 96%|█████████▌| 100/104 [00:42<00:01,  3.94it/s]
 97%|█████████▋| 101/104 [00:42<00:00,  4.18it/s]
 99%|█████████▉| 103/104 [00:43<00:00,  6.11it/s]
100%|██████████| 104/104 [00:43<00:00,  6.56it/s]
100%|██████████| 104/104 [00:43<00:00,  2.41it/s]
  Saved in 44.44s
Creating segmentations with TotalSegmentator AI...
Total Segmentator arguments: ['-i', '/tmp/Slicer-i/__SlicerTemp__2023-11-26_09+37+05.403/total-segmentator-input.nii', '-o', '/tmp/Slicer-i/__SlicerTemp__2023-11-26_09+37+05.403/segmentation', '--ml', '--task', 'bones_extremities']
/home/i/Downloads/Slicer-5.4.0-linux-amd64/lib/Python/bin/TotalSegmentator:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import require
/home/i/Downloads/Slicer-5.4.0-linux-amd64/lib/Python/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "

If you use this tool please cite: https://doi.org/10.48550/arXiv.2208.05868

No GPU detected. Running on CPU. This can be very slow. The '--fast' option can help to some extend.

This model is only available upon purchase of a license (free licenses available for academic projects).
Contact jakob.wasserthal@usb.ch if you are interested.

Importing segmentation results...
```

</p>
</details>

**Comment by ivanstepanovftw** [comment]
Same for `tissue_types`

**Comment by MOHeller** [comment]
I think you will find that slicer 5.4 only supports TotalSegmentator v1, and the tasks you try to run are only supported in v2 afaik.
You would need to update to slicer 5.5 to use TotalSegmentator v2 (where the tasks in question do work).

see the discussion e.g. here:
https://discourse.slicer.org/t/problem-running-totalsegmentator-in-slicer-5-4/32491

**Comment by philippeif** [comment]
Hello,

I tried TotalSegmentator v2 within Slicer 5.6.1.
The limbs are missing (below the knee / humerus) on all CTs I tried (5).

Version 5.5 is mentioned there but not available in the collection of older slicer packages on Kitware's site (5.4->5.6).

Which version should be used for v2?

Thanks
Philippe
PS: posted on slicer discourse as well
