### ISSUE TITLE
Pretrained model format and Fine tuning 

### ISSUE THREAD

**Issue by LongChenCV** [wasserth/TotalSegmentator#246]
I'm trying to fine-tune the pretrained model on my own dataset using the command, the pretrained model format is  .model, when I run the fine-tuning command:

**nnUNetv2_train 101 3d_fullres 0 -tr nnUNetTrainerNoMirroring -pretrained_weights ~/fold_0/model_final_checkpoint.model**

The following error occurs, I think this is because .pth is required by nnUNetv2_train rather than .model. Is there any solution to fine-tune the pretrained model on my own dataset? Thanks! 

Traceback (most recent call last):
File "/mnt/storage/home/lchen6/anaconda3/envs/totalseg/bin/nnUNetv2_train", line 8, in
sys.exit(run_training_entry())
File "/mnt/storage/home/lchen6/anaconda3/envs/totalseg/lib/python3.9/site-packages/nnunetv2/run/run_training.py", line 252, in run_training_entry
run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
File "/mnt/storage/home/lchen6/anaconda3/envs/totalseg/lib/python3.9/site-packages/nnunetv2/run/run_training.py", line 188, in run_training
maybe_load_checkpoint(nnunet_trainer, continue_training, only_run_validation, pretrained_weights)
File "/mnt/storage/home/lchen6/anaconda3/envs/totalseg/lib/python3.9/site-packages/nnunetv2/run/run_training.py", line 93, in maybe_load_checkpoint
load_pretrained_weights(nnunet_trainer.network, pretrained_weights_file, verbose=True)
File "/mnt/storage/home/lchen6/anaconda3/envs/totalseg/lib/python3.9/site-packages/nnunetv2/run/load_pretrained_weights.py", line 12, in load_pretrained_weights
pretrained_dict = saved_model['network_weights']
KeyError: 'network_weights'

**Comment by wasserth** [comment]
It set seems that you are trying to load nnunet v1 weights into nnunet v2. That does not work. Please get the latest weights of Totalegmentator v2. These are nnunet v2 weights.

https://github.com/wasserth/TotalSegmentator/releases/tag/v2.0.0-weights

**Comment by IanDragon** [comment]
Thanks very much!

**Comment by LongChenCV** [comment]
Thanks very much!
