### ISSUE TITLE
Currently Unable to download the weights for Task Body on version 2.0.5

### ISSUE THREAD

**Issue by 0LambSauce0** [wasserth/TotalSegmentator#267]
During execution of Task body, The code throws an error stating its unable to locate the weights while all other tasks seem to work fine. 

Total Segmentator failed for task body with error: Traceback (most recent call last):
  File "/home/tkkhan/.conda/envs/tb/bin/TotalSegmentator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tkkhan/.conda/envs/tb/lib/python3.11/site-packages/totalsegmentator/bin/TotalSegmentator.py", line 127, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "/home/tkkhan/.conda/envs/tb/lib/python3.11/site-packages/totalsegmentator/python_api.py", line 293, in totalsegmentator
    seg_img, ct_img = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tkkhan/.conda/envs/tb/lib/python3.11/site-packages/totalsegmentator/nnunet.py", line 395, in nnUNet_predict_image
    nnUNetv2_predict(tmp_dir, tmp_dir, task_id, model, folds, trainer, tta,
  File "/home/tkkhan/.conda/envs/tb/lib/python3.11/site-packages/totalsegmentator/nnunet.py", line 178, in nnUNetv2_predict
    predict_from_raw_data(dir_in,
  File "/home/tkkhan/.conda/envs/tb/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 159, in predict_from_raw_data
    load_what_we_need(model_training_output_dir, use_folds, checkpoint_name)
  File "/home/tkkhan/.conda/envs/tb/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 73, in load_what_we_need
    dataset_json = load_json(join(model_training_output_dir, 'dataset.json'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tkkhan/.conda/envs/tb/lib/python3.11/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 68, in load_json
    with open(file, 'r') as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkkhan/.totalsegmentator/nnunet/results/Dataset299_body_1559subj/nnUNetTrainer__nnUNetPlans__3d_fullres/dataset.json'
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x7f2ef47ce850>
AttributeError: 'DummyFile' object has no attribute 'flush'

**Comment by MeldaYeghia** [comment]
I'm having a similar problem for some time now using the default task of total body segmentation. The model is not being downloaded/loaded. I tested the same code with the task 'body' and it works fine! My input is a whole body CT nifti file. I'm using python 3.10 with pytorch 2.2.1 and totalsegmentator 2.1.0. Here's the error I'm getting:

Traceback (most recent call last):
  File "/home/m.yegh/miniconda3/envs/total_seg_env_g/bin/TotalSegmentator", line 8, in <module>
    sys.exit(main())
  File "/home/m.yegh/miniconda3/envs/total_seg_env_g/lib/python3.10/site-packages/totalsegmentator/bin/TotalSegmentator.py", line 132, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "/home/m.yegh/miniconda3/envs/total_seg_env_g/lib/python3.10/site-packages/totalsegmentator/python_api.py", line 326, in totalsegmentator
    seg_img, ct_img = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
  File "/home/m.yegh/miniconda3/envs/total_seg_env_g/lib/python3.10/site-packages/totalsegmentator/nnunet.py", line 440, in nnUNet_predict_image
    nnUNetv2_predict(tmp_dir, tmp_dir, tid, model, folds, trainer, tta,
  File "/home/m.yegh/miniconda3/envs/total_seg_env_g/lib/python3.10/site-packages/totalsegmentator/nnunet.py", line 242, in nnUNetv2_predict
    predictor.initialize_from_trained_model_folder(
  File "/home/m.yegh/miniconda3/envs/total_seg_env_g/lib/python3.10/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 85, in initialize_from_trained_model_folder
    checkpoint = torch.load(join(model_training_output_dir, f'fold_{f}', checkpoint_name),
  File "/home/m.yegh/miniconda3/envs/total_seg_env_g/lib/python3.10/site-packages/torch/serialization.py", line 1005, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/m.yegh/miniconda3/envs/total_seg_env_g/lib/python3.10/site-packages/torch/serialization.py", line 457, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
