### ISSUE TITLE
Error while installing python package on Ubuntu 20.04

### ISSUE THREAD

**Issue by sunil-27** [wasserth/TotalSegmentator#304]
Traceback (most recent call last):
  File "/slicer/Slicer-5.2.1-linux-amd64/bin/Python/slicer/util.py", line 2961, in tryWithErrorDisplay
    yield
  File "/slicer/Slicer-5.2.1-linux-amd64/NA-MIC/Extensions-31317/TotalSegmentator/lib/Slicer-5.2/qt-scripted-modules/TotalSegmentator.py", line 255, in onApplyButton
    self.logic.setupPythonRequirements()
  File "/slicer/Slicer-5.2.1-linux-amd64/NA-MIC/Extensions-31317/TotalSegmentator/lib/Slicer-5.2/qt-scripted-modules/TotalSegmentator.py", line 624, in setupPythonRequirements
    slicer.util.pip_install(self.totalSegmentatorPythonPackageDownloadUrl)
  File "/slicer/Slicer-5.2.1-linux-amd64/bin/Python/slicer/util.py", line 3571, in pip_install
    _executePythonModule('pip', args)
  File "/slicer/Slicer-5.2.1-linux-amd64/bin/Python/slicer/util.py", line 3533, in _executePythonModule
    logProcessOutput(proc)
  File "/slicer/Slicer-5.2.1-linux-amd64/bin/Python/slicer/util.py", line 3502, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['/slicer/Slicer-5.2.1-linux-amd64/bin/../bin/PythonSlicer', '-m', 'pip', 'install', 'https://github.com/wasserth/TotalSegmentator/archive/ecf84f9e59b84dddb447e2b13542f58c29ee4c6a.zip']' returned non-zero exit status 1.

**Comment by jamesobutler** [comment]
Please try with latest Slicer stable (currently 5.6.1) which you can download from https://download.slicer.org/. There have been updates to the latest SlicerTotalSegmentator extension that is available in the latest stable release that is not in the older Slicer 5.2.1 that you are using. Please report back after trying the latest Slicer stable version.
