### ISSUE TITLE
Issue with MR model - Error with `build_network_architecture` in nnUnet

### ISSUE THREAD

**Issue by rcorredorj** [wasserth/TotalSegmentator#315]
Similar post :
_Originally posted by @wasserth in https://github.com/wasserth/TotalSegmentator/issues/234#issuecomment-1822707567_

Hi,

Did you guys find a solution to this? I just installed the last version to perform a segmentation with the new model for MR images and I'm getting the following : 

**(AI_Sandbox) PS C:\> TotalSegmentator -i "C:\temp\t1_vibe_dixon_tra_dinamico_W_Series0028.nii.gz" --device cpu --fast --statistics --ml --task total_mr -o "C:\temp\LIVER" --verbose > "C:\temp\LIVER\log.txt"**

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\tmp\miniconda3\envs\AI_Sandbox\Scripts\TotalSegmentator.exe\__main__.py", line 7, in <module>
  File "C:\tmp\miniconda3\envs\AI_Sandbox\Lib\site-packages\totalsegmentator\bin\TotalSegmentator.py", line 132, in main
    totalsegmentator(args.input, args.output, args.ml, args.nr_thr_resamp, args.nr_thr_saving,
  File "C:\tmp\miniconda3\envs\AI_Sandbox\Lib\site-packages\totalsegmentator\python_api.py", line 379, in totalsegmentator
    seg_img, ct_img, stats = nnUNet_predict_image(input, output, task_id, model=model, folds=folds,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\miniconda3\envs\AI_Sandbox\Lib\site-packages\totalsegmentator\nnunet.py", line 471, in nnUNet_predict_image
    nnUNetv2_predict(tmp_dir, tmp_dir, task_id, model, folds, trainer, tta,
  File "C:\tmp\miniconda3\envs\AI_Sandbox\Lib\site-packages\totalsegmentator\nnunet.py", line 242, in nnUNetv2_predict
    predictor.initialize_from_trained_model_folder(
  File "**C:\tmp\miniconda3\envs\AI_Sandbox\Lib\site-packages\nnunetv2\inference\predict_from_raw_data.py**", line 101, in **initialize_from_trained_model_folder**
    network = trainer_class.build_network_architecture(plans_manager, dataset_json, configuration_manager,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**AttributeError: 'NoneType' object has no attribute 'build_network_architecture'**

Thanks!

RaC

**Comment by rcorredorj** [comment]
Issue solved. Re-installing in a clean virtual env, I guess there was a discrepancy with certain dependencies installed previously.
