### ISSUE TITLE
liver_vessels issue

### ISSUE THREAD

**Issue by mingtian126** [wasserth/TotalSegmentator#381]
Hello,
I'm working on segmenting the liver vessels. Here's what I did:
output_img = totalsegmentator(input_img,preview=False,roi_subset=['liver_vessels'])
It's processing till Resampling..., then gave me the following error:

Resampling...
Traceback (most recent call last):
  File "/mnt/test_segmentator_nifti.py", line 19, in <module>
    output_img = totalsegmentator(input_img,preview=False,roi_subset=['liver_vessels'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/site-packages/totalsegmentator/python_api.py", line 358, in totalsegmentator
    crop_mask[organ_seg_data == class_map_inv[roi]] = 1
                                ~~~~~~~~~~~~~^^^^^
KeyError: 'liver_vessels'

Please help,
Thank you!

**Comment by wasserth** [comment]
You have to set liver_vessels as `task` not as `roi_subset`.

**Comment by mingtian126** [comment]
Thanks for your response. I tried task as well, here's the error message:

Downloading model for Task 8 ...
Traceback (most recent call last):
  File "/mnt/DataDisc/segPythonNew/test_segmentator_nifti.py", line 18, in <module>
    output_img = totalsegmentator(input_img,preview=False, task='liver_vessels')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/site-packages/totalsegmentator/python_api.py", line 306, in totalsegmentator
    download_pretrained_weights(task_id)
  File "/home/anaconda3/lib/python3.11/site-packages/totalsegmentator/libs.py", line 317, in download_pretrained_weights
    download_url_and_unpack(WEIGHTS_URL, config_dir)
  File "/home/anaconda3/lib/python3.11/site-packages/totalsegmentator/libs.py", line 129, in download_url_and_unpack
    raise e
  File "/home/anaconda3/lib/python3.11/site-packages/totalsegmentator/libs.py", line 112, in download_url_and_unpack
    with requests.get(url, stream=True) as r:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/yijingwu/anaconda3/lib/python3.11/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/home/yijingwu/anaconda3/lib/python3.11/site-packages/requests/models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'todo': No scheme supplied. Perhaps you meant https://todo?

Please help,
Thank you!

**Comment by wasserth** [comment]
which totalsegmentator version are you using? maybe you have to upgrade

**Comment by mingtian126** [comment]
@wasserth Thanks for your quick response. Yes, I upgrade it and works like a charm!
One more question, is there a  guideline when to use "task" and when to use "roi_subset"?
Thanks again for the great work!
