### ISSUE TITLE
Error during the anatomical segmentation using 3D Slicer and TotalSegmentor

### ISSUE THREAD

**Issue by kjellis1959** [wasserth/TotalSegmentator#41]
Hi, 
Using 3D Slicer 5.2.1 and the new tool for anatomical segmentation of CT images, TotalSegmentor we get the following error: 

```
Processing started
Writing input file to C:/Users/NordicCAD/AppData/Local/Temp/Slicer/__SlicerTemp__2022-12-21_12+57+32.255/total-segmentator-input.nii
Creating segmentations with TotalSegmentator AI...
Total Segmentator arguments: ['-i', 'C:/Users/NordicCAD/AppData/Local/Temp/Slicer/__SlicerTemp__2022-12-21_12+57+32.255/total-segmentator-input.nii', '-o', 'C:/Users/NordicCAD/AppData/Local/Temp/Slicer/__SlicerTemp__2022-12-21_12+57+32.255/segmentation', '--ml', '--task', 'total']


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

preprocessing C:\Users\NORDIC~1\AppData\Local\Temp\nnunet_tmp_pun2y8kt\s01.nii.gz
using preprocessor GenericPreprocessor
before crop: (1, 331, 261, 261) after crop: (1, 331, 261, 261) spacing: [1.5 1.5 1.5]

no resampling necessary
no resampling necessary
before: {'spacing': array([1.5, 1.5, 1.5]), 'spacing_transposed': array([1.5, 1.5, 1.5]), 'data.shape (data is transposed)': (1, 331, 261, 261)}
after:  {'spacing': array([1.5, 1.5, 1.5]), 'data.shape (data is resampled)': (1, 331, 261, 261)}

(1, 331, 261, 261)
This worker has ended successfully, no errors to report


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

force_separate_z: None interpolation order: 0


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

preprocessing C:\Users\NORDIC~1\AppData\Local\Temp\nnunet_tmp_pun2y8kt\s01.nii.gz
using preprocessor GenericPreprocessor
before crop: (1, 331, 261, 261) after crop: (1, 331, 261, 261) spacing: [1.5 1.5 1.5]

no resampling necessary
no resampling necessary
before: {'spacing': array([1.5, 1.5, 1.5]), 'spacing_transposed': array([1.5, 1.5, 1.5]), 'data.shape (data is transposed)': (1, 331, 261, 261)}
after:  {'spacing': array([1.5, 1.5, 1.5]), 'data.shape (data is resampled)': (1, 331, 261, 261)}

(1, 331, 261, 261)
This worker has ended successfully, no errors to report


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

force_separate_z: None interpolation order: 0


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

preprocessing C:\Users\NORDIC~1\AppData\Local\Temp\nnunet_tmp_pun2y8kt\s01.nii.gz
using preprocessor GenericPreprocessor
before crop: (1, 331, 261, 261) after crop: (1, 331, 261, 261) spacing: [1.5 1.5 1.5]

no resampling necessary
no resampling necessary
before: {'spacing': array([1.5, 1.5, 1.5]), 'spacing_transposed': array([1.5, 1.5, 1.5]), 'data.shape (data is transposed)': (1, 331, 261, 261)}
after:  {'spacing': array([1.5, 1.5, 1.5]), 'data.shape (data is resampled)': (1, 331, 261, 261)}

(1, 331, 261, 261)
This worker has ended successfully, no errors to report


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

force_separate_z: None interpolation order: 0
Traceback (most recent call last):
  File "C:\Users\NordicCAD\AppData\Local\NA-MIC\Slicer 5.2.1\lib\Python\Scripts\TotalSegmentator", line 201, in <module>
    main()
  File "C:\Users\NordicCAD\AppData\Local\NA-MIC\Slicer 5.2.1\lib\Python\Scripts\TotalSegmentator", line 179, in main
    seg = nnUNet_predict_image(args.input, args.output, task_id, model=model, folds=folds,
  File "C:\Users\NordicCAD\AppData\Local\NA-MIC\Slicer 5.2.1\lib\Python\Lib\site-packages\totalsegmentator\nnunet.py", line 215, in nnUNet_predict_image
    nnUNet_predict(tmp_dir, tmp_dir, tid, model, folds, trainer, tta)
  File "C:\Users\NordicCAD\AppData\Local\NA-MIC\Slicer 5.2.1\lib\Python\Lib\site-packages\totalsegmentator\nnunet.py", line 106, in nnUNet_predict
    predict_from_folder(model_folder_name, dir_in, dir_out, folds, save_npz, num_threads_preprocessing,
  File "C:\Users\NordicCAD\AppData\Local\NA-MIC\Slicer 5.2.1\lib\Python\Lib\site-packages\nnunet\inference\predict.py", line 616, in predict_from_folder
    shutil.copy(join(model, 'plans.pkl'), output_folder)
  File "C:\Users\NordicCAD\AppData\Local\NA-MIC\Slicer 5.2.1\lib\Python\Lib\shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\NordicCAD\AppData\Local\NA-MIC\Slicer 5.2.1\lib\Python\Lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\NordicCAD\\.totalsegmentator\\nnunet\\results\\nnUNet\\3d_fullres\\Task254_TotalSegmentator_part4_muscles_1139subj\\nnUNetTrainerV2_ep4000_nomirror__nnUNetPlansv2.1\\plans.pkl'
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x000001207987A370>
AttributeError: 'DummyFile' object has no attribute 'flush'
Resampling...
  Resampled in 18.95s
Predicting part 0 of 5 ...
Predicting part 1 of 5 ...
Predicting part 2 of 5 ...
Predicting part 3 of 5 ...
```

![image](https://user-images.githubusercontent.com/121170486/208903970-e3e61882-5964-4e26-8252-368a6e2f4343.png)

**Comment by carlpe** [comment]
You will need these items if they are missing, in the "muscle" folder:

folds.pkl and the "fold_0" subdirectory

`C:\Users\YOURUSER\.totalsegmentator\nnunet\results\nnUNet\3d_fullres\Task254_TotalSegmentator_part4_muscles_1139subj\nnUNetTrainerV2_ep4000_nomirror__nnUNetPlansv2.1
`
![image](https://user-images.githubusercontent.com/54416001/209156320-f510d3a0-9acb-47b0-b494-a32bfd6c7f17.png)
