### ISSUE TITLE
Error Message when running total CT segmentation

### ISSUE THREAD

**Issue by MattAWard** [wasserth/TotalSegmentator#61]
When trying to use TotalSegmentator to segment a thoracic CT data set the following error message is displayed:

```
Traceback (most recent call last):
  File "C:\ProgramData\NA-MIC\Slicer 5.2.1\bin\Python\slicer\util.py", line 2961, in tryWithErrorDisplay
    yield
  File "C:/ProgramData/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/TotalSegmentator/lib/Slicer-5.2/qt-scripted-modules/TotalSegmentator.py", line 264, in onApplyButton
    self.logic.process(self.ui.inputVolumeSelector.currentNode(), self.ui.outputSegmentationSelector.currentNode(),
  File "C:/ProgramData/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/TotalSegmentator/lib/Slicer-5.2/qt-scripted-modules/TotalSegmentator.py", line 749, in process
    self.logProcessOutput(proc)
  File "C:/ProgramData/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/TotalSegmentator/lib/Slicer-5.2/qt-scripted-modules/TotalSegmentator.py", line 656, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['C:/ProgramData/NA-MIC/Slicer 5.2.1/bin/../bin\\PythonSlicer.EXE', 'C:\\ProgramData\\NA-MIC\\Slicer 5.2.1\\lib\\Python\\Scripts\\TotalSegmentator', '-i', 'C:/Users/Administrator/AppData/Local/Temp/2/Slicer/__SlicerTemp__2023-01-27_14+19+32.319/total-segmentator-input.nii', '-o', 'C:/Users/Administrator/AppData/Local/Temp/2/Slicer/__SlicerTemp__2023-01-27_14+19+32.319/segmentation', '--ml', '--task', 'total', '--fast']' returned non-zero exit status 120.
```

Any idea what is causing this problem? The same error appears when running a Fast or Normal segmentation and for whichever segmentation task is selected.

**Comment by denbonte** [comment]
Hey @MattAWard!

I had the pleasure to chat with @lassoan these days, and he mentioned a similar issue I was looking into as well (as we are testing various dockerized versions of TotalSegmentator on multiple machines, inside and outside Slicer).

It looks like [the thread at this link](https://discourse.slicer.org/t/totalsegmentator-error-at-first-run-command-python-scripts-totalsegmentator-returned-non-zero-exit-status-120/26755) could help you out as well.

**Comment by MattAWard** [comment]
Brill thanks @denbonte, I'll try a couple of things suggested in the thread.
