### ISSUE TITLE
 Run TotalSegmentator error

### ISSUE THREAD

**Issue by huangguoqing** [wasserth/TotalSegmentator#93]
When run TotalSegmentator -i ct.nii.gz -o segmentations，I Meet the error:

Downloading pretrained weights for Task 251 (~230MB) ...
Traceback (most recent call last):
  File "/home/lung/anaconda3/envs/totalseg/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/lung/anaconda3/envs/totalseg/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/lung/anaconda3/envs/totalseg/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/6802342/files/Task251_TotalSegmentator_part1_organs_1139subj.zip?download=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5c3d87e2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by wasserth** [comment]
It seems that you can not connect to the zenodo server to download the weights. Can you try again later or from a different internet network?

**Comment by xiaoli26** [comment]
The solution is download all the weight file from the zenodo manually and paste the unzip files to the 3d_fullres folder "C:\Users\XXXX.totalsegmentator\nnunet\results\nnUNet\3d_fullres"
